import localFont from "next/font/local";
import "./globals.css";

const dinNext = localFont({
  src: "./fonts/DINNextW1G-Regular.otf",
  variable: "--font-din-next",
  weight: "100 900",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dinNext.variable}  antialiased bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
